import { type NextPage } from 'next';
import Head from 'next/head';

import { CheckboxTableCell, NameTableCell, NutrientTableCell, TableRow } from '@components/TableComponents';

import SearchBar from '../components/Search';

interface ProductItem {
  name: string;
  fats: number;
  salt: number;
  energy: number;
  proteins: number;
  carbs: number;
}

const data: ProductItem[] = [
  {
    name: 'Banany v cokolade',
    fats: 34,
    carbs: 12,
    proteins: 42,
    salt: 29,
    energy: 1018,
  },
  {
    name: 'Bravcove Mäso',
    fats: 50,
    carbs: 47,
    proteins: 42,
    salt: 5,
    energy: 518,
  },
  {
    name: 'Omamne Latky',
    fats: 5,
    carbs: 40,
    proteins: 25,
    salt: 40,
    energy: 949,
  },
  {
    name: 'Chelba so sunkou a maslom a syrom',
    fats: 34,
    carbs: 21,
    proteins: 37,
    salt: 16,
    energy: 890,
  },
  {
    name: 'Banany v cokolade',
    fats: 2,
    carbs: 46,
    proteins: 49,
    salt: 9,
    energy: 763,
  },
];

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="my-16 md:my-32">
        <div className="mx-auto max-w-full rounded-lg ">
          <div className="px-4 text-center text-teal-400">
            <h1 className="font-poppins text-6xl">Food Database</h1>
            <div className="flex">
              <p className="tooltip-bottom mx-auto w-fit" data-tooltip="Test">
                Bottom
              </p>
              <p className="tooltip-left mx-auto w-fit" data-tooltip="Test">
                Left
              </p>
              <p className="tooltip-right mx-auto w-fit" data-tooltip="Test">
                Right
              </p>
              <p className="tooltip-top mx-auto w-fit" data-tooltip="Test">
                Top
              </p>
            </div>
          </div>
        </div>
      </header>
      <nav className="mb-16 md:mb-32">
        <SearchBar />
      </nav>
      <main className="mx-auto w-full max-w-[100vw] px-0 lg:w-[90%] lg:min-w-[65rem] lg:px-4 xl:w-[90%] xl:min-w-[80rem] 2xl:w-[50%] 2xl:min-w-[87rem]">
        <div className="overflow-y-scroll bg-white lg:rounded-lg">
          <table className="min-w-[48rem] max-w-full">
            <thead className="flex flex-row rounded-2xl px-0 pb-1 pt-2 lg:px-4 lg:pt-2">
              <tr className="flex w-full min-w-full flex-row bg-slate-100 lg:rounded-md ">
                <th
                  data-tooltip="Kokotina velka pocivaiojsdoajsdoiaspdmpmsa"
                  className="inline-flex w-fit items-center py-2 px-4 text-left font-bold md:rounded-l-md"
                >
                  <input disabled className="h-5 w-5 cursor-pointer disabled:cursor-not-allowed" type="checkbox" />
                </th>
                <th className="inline-flex min-w-[12rem] max-w-[12rem] md:min-w-[16rem] md:max-w-[16rem]">
                  <div className="py-2 text-left font-bold">Name</div>
                </th>
                <th className="mx-auto inline-flex min-w-[6rem] max-w-[6rem] justify-center py-2 px-4 font-bold">
                  energy
                </th>
                <th className="mx-auto inline-flex min-w-[6rem] max-w-[6rem] justify-center py-2 px-4 font-bold">
                  fats
                </th>
                <th className="mx-auto inline-flex min-w-[6rem] max-w-[6rem] justify-center py-2 px-4 font-bold">
                  carbs
                </th>
                <th className="mx-auto inline-flex min-w-[6rem] max-w-[6rem] justify-center py-2 px-4 font-bold">
                  proteins
                </th>
                <th className="mx-auto inline-flex min-w-[6rem] max-w-[6rem] justify-center py-2 px-4 font-bold">
                  salt
                </th>
              </tr>
            </thead>
            <tbody className="lg:px-4">
              {data.map((item: ProductItem, index) => (
                <TableRow key={index}>
                  <CheckboxTableCell>
                    <input disabled className="h-5 w-5 cursor-pointer disabled:cursor-not-allowed" type="checkbox" />
                  </CheckboxTableCell>
                  <NameTableCell>{item.name}</NameTableCell>
                  <NutrientTableCell>{item.fats}</NutrientTableCell>
                  <NutrientTableCell>{item.carbs}</NutrientTableCell>
                  <NutrientTableCell>{item.proteins}</NutrientTableCell>
                  <NutrientTableCell>{item.carbs}</NutrientTableCell>
                  <NutrientTableCell>{item.salt}</NutrientTableCell>
                </TableRow>
              ))}
            </tbody>
          </table>
        </div>
      </main>
    </>
  );
};

export default Home;
