import { type NextPage } from 'next';
import Head from 'next/head';
import type { Product } from '@type/Product';

import { Modal } from '@components/Modal';
import { TableRow } from '@components/TableComponents';
import { TableColumnHeading, TableColumnHeadingSortable } from '@components/TableComponents';

import SearchBar from '../components/Search';

const data: Product[] = [
  {
    name: 'Kuracie Prsia',
    brand: 'Ferdinand',
    description: 'eget, ipsum. Donec sollicitudin adipiscing ligula. Aenean gravida nunc sed pede.',
    id: '1',
    energy: 217,
    fats: 56,
    saturatedFats: 30,
    unsaturatedMonoFats: 33,
    unsaturatedPolyFats: 66,
    proteins: 39,
    carbohydrates: 54,
    sugar: 24,
    fiber: 3,
    salt: 4,
  },
  {
    name: 'Kuracie Prsia',
    brand: 'Bruno',
    description:
      'Vestibulum ut eros non enim commodo hendrerit. Donec porttitor tellus non magna. Nam ligula elit, pretium et, rutrum non,',
    id: '2',
    energy: 473,
    fats: 16,
    saturatedFats: 32,
    unsaturatedMonoFats: 69,
    unsaturatedPolyFats: 51,
    proteins: 54,
    carbohydrates: 28,
    sugar: 55,
    fiber: 11,
    salt: 8,
  },
  {
    name: 'Chleba',
    brand: 'Xaviera',
    description:
      'Ut sagittis lobortis mauris. Suspendisse aliquet molestie tellus. Aenean egestas hendrerit neque. In ornare sagittis felis. Donec tempor, est',
    id: '3',
    energy: 424,
    fats: 55,
    saturatedFats: 9,
    unsaturatedMonoFats: 30,
    unsaturatedPolyFats: 42,
    proteins: 10,
    carbohydrates: 13,
    sugar: 29,
    fiber: 35,
    salt: 10,
  },
  {
    name: 'Kuracie Prsia',
    brand: 'Drake',
    description: 'nec tempus scelerisque, lorem ipsum sodales purus, in molestie tortor nibh sit amet',
    id: '4',
    energy: 365,
    fats: 1,
    saturatedFats: 4,
    unsaturatedMonoFats: 3,
    unsaturatedPolyFats: 20,
    proteins: 29,
    carbohydrates: 31,
    sugar: 13,
    fiber: 12,
    salt: 3,
  },
  {
    name: 'Chleba',
    brand: 'Robert',
    description:
      'Nunc quis arcu vel quam dignissim pharetra. Nam ac nulla. In tincidunt congue turpis. In condimentum. Donec at arcu. Vestibulum ante',
    id: '5',
    energy: 157,
    fats: 12,
    saturatedFats: 5,
    unsaturatedMonoFats: 5,
    unsaturatedPolyFats: 23,
    proteins: 33,
    carbohydrates: 48,
    sugar: 61,
    fiber: 64,
    salt: 2,
  },
];

const Home: NextPage = () => {
  return (
    <>
      <Modal />
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="my-8 md:my-16">
        <div className="mx-auto max-w-full rounded-lg ">
          <div className="px-4 text-center text-teal-400">
            <h1 className="font-poppins text-6xl">Food Database</h1>
          </div>
        </div>
      </header>
      <nav className="mx-2 mb-4 xs:mx-8 md:mb-8">
        <SearchBar />
      </nav>
      <nav className="mx-auto w-full">
        <div className="bg-white lg:rounded-lg"></div>
      </nav>
      <main className="mx-auto w-full max-w-[100vw] px-0 lg:w-[90%] lg:min-w-[60rem]  xl:w-[90%] xl:min-w-[80rem] 2xl:w-[50%] 2xl:min-w-[87rem]">
        <div className="overflow-y-scroll bg-white lg:rounded-lg">
          <table className="min-w-fit max-w-full">
            <thead className="flex flex-row rounded-2xl px-0 pb-2 pt-2 text-slate-600 lg:px-4 lg:pt-2">
              <tr className="flex w-full min-w-full flex-row bg-slate-100 lg:rounded-md ">
                <TableColumnHeading dataTooltip="This feature is not yet available.">
                  <input disabled className="h-5 w-5 cursor-pointer disabled:cursor-not-allowed" type="checkbox" />
                </TableColumnHeading>
                <TableColumnHeadingSortable className="inline-flex min-w-[12rem] max-w-[12rem] cursor-pointer items-center py-2 text-left font-bold transition-colors focus:text-teal-400 md:min-w-[16rem] md:max-w-[16rem]">
                  name
                </TableColumnHeadingSortable>
                <TableColumnHeadingSortable>energy</TableColumnHeadingSortable>
                <TableColumnHeadingSortable>fats</TableColumnHeadingSortable>
                <TableColumnHeadingSortable>carbs</TableColumnHeadingSortable>
                <TableColumnHeadingSortable>proteins</TableColumnHeadingSortable>
                <TableColumnHeadingSortable>salt</TableColumnHeadingSortable>
              </tr>
            </thead>
            <tbody className="lg:px-4">
              {data.map((item, index) => (
                <TableRow key={index} data={item} />
              ))}
            </tbody>
          </table>
        </div>
      </main>
    </>
  );
};

export default Home;
