import { type NextPage } from 'next';
import Head from 'next/head';

import { Header } from '@components/Header';
import { Main } from '@components/Main';
import { Modal } from '@components/Modal';
import { NavigationBar } from '@components/NavigationBar';
import { Table } from '@components/TableComponents';

const Home: NextPage = () => {
  return (
    <>
      <Modal />
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <NavigationBar />
      <Main>
        <button>Klik me kkt</button>
        <div className="overflow-y-scroll bg-white lg:rounded-lg">
          <Table />
        </div>
      </Main>
    </>
  );
};

export default Home;
