import { useContext } from 'react';
import { type NextPage } from 'next';
import Head from 'next/head';

import { IconButton } from '@components/Buttons';
import { Header } from '@components/Header';
import { Main } from '@components/Main';
import { Confirmation, Modal } from '@components/Modal';
import { ConfirmationDialog } from '@components/Modal/Data';
import { AddProductModal } from '@components/Modal/Data/addProductModal';
import { NavigationBar } from '@components/NavigationBar';
import { Table } from '@components/TableComponents';

import { NewModalContext } from '@context/NewModalContext';

import { AddIcon, WarningIcon } from '@assets/icons';

const Home: NextPage = () => {
  const { open } = useContext(NewModalContext);

  const handleClick = () => {
    open(
      <AddProductModal />,
      <ConfirmationDialog
        title="Discard changes?"
        description="Are you sure you want to discard changes?"
        negativeButtonTitle="Discard"
        positiveButtonTitle="Continue"
      />,
    );
  };

  return (
    <>
      <Modal />
      <Confirmation />
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <NavigationBar />
      <Main>
        <div className="flex justify-end gap-x-2 py-4 px-2 sm:px-6 lg:px-0">
          <IconButton
            onClick={handleClick}
            colorType="green"
            icon={AddIcon}
            tooltip={'Add product to database'}
            tooltipPosition="top"
          />
          <IconButton colorType="yellow" icon={WarningIcon} />
        </div>
        <div className="overflow-y-scroll bg-white lg:rounded-lg">
          <Table />
        </div>
      </Main>
    </>
  );
};

export default Home;
